-- Description: Insert backtracking recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('N과 M (1)', 'https://www.acmicpc.net/problem/15649', 'BACKTRACKING', 'BOJ', 8),
('N과 M (3)', 'https://www.acmicpc.net/problem/15651', 'BACKTRACKING', 'BOJ', 8),
('N과 M (5)', 'https://www.acmicpc.net/problem/15654', 'BACKTRACKING', 'BOJ', 8),
('N과 M (2)', 'https://www.acmicpc.net/problem/15650', 'BACKTRACKING', 'BOJ', 8),
('N과 M (7)', 'https://www.acmicpc.net/problem/15656', 'BACKTRACKING', 'BOJ', 8),
('N과 M (4)', 'https://www.acmicpc.net/problem/15652', 'BACKTRACKING', 'BOJ', 8),
('N과 M (8)', 'https://www.acmicpc.net/problem/15657', 'BACKTRACKING', 'BOJ', 8),
('N과 M (6)', 'https://www.acmicpc.net/problem/15655', 'BACKTRACKING', 'BOJ', 8),
('외판원 순회 2', 'https://www.acmicpc.net/problem/10971', 'BACKTRACKING', 'BOJ', 9),
('부분수열의 합', 'https://www.acmicpc.net/problem/1182', 'BACKTRACKING', 'BOJ', 9),
('N과 M (9)', 'https://www.acmicpc.net/problem/15663', 'BACKTRACKING', 'BOJ', 9),
('N과 M (11)', 'https://www.acmicpc.net/problem/15665', 'BACKTRACKING', 'BOJ', 9),
('N과 M (10)', 'https://www.acmicpc.net/problem/15664', 'BACKTRACKING', 'BOJ', 9),
('N과 M (12)', 'https://www.acmicpc.net/problem/15666', 'BACKTRACKING', 'BOJ', 9),
('스타트와 링크', 'https://www.acmicpc.net/problem/14889', 'BACKTRACKING', 'BOJ', 10),
('연산자 끼워넣기', 'https://www.acmicpc.net/problem/14888', 'BACKTRACKING', 'BOJ', 10),
('애너그램', 'https://www.acmicpc.net/problem/6443', 'BACKTRACKING', 'BOJ', 11),
('줄어드는 수', 'https://www.acmicpc.net/problem/1174', 'BACKTRACKING', 'BOJ', 11),
('선발 명단', 'https://www.acmicpc.net/problem/3980', 'BACKTRACKING', 'BOJ', 11),
('계란으로 계란치기', 'https://www.acmicpc.net/problem/16987', 'BACKTRACKING', 'BOJ', 11),
('넴모넴모 (Easy)', 'https://www.acmicpc.net/problem/14712', 'BACKTRACKING', 'BOJ', 11),
('가르침', 'https://www.acmicpc.net/problem/1062', 'BACKTRACKING', 'BOJ', 12),
('스도쿠', 'https://www.acmicpc.net/problem/2580', 'BACKTRACKING', 'BOJ', 12),
('N-Queen', 'https://www.acmicpc.net/problem/9663', 'BACKTRACKING', 'BOJ', 12),
('무기 공학', 'https://www.acmicpc.net/problem/18430', 'BACKTRACKING', 'BOJ', 12),
('좋은수열', 'https://www.acmicpc.net/problem/2661', 'BACKTRACKING', 'BOJ', 12),
('죽음의 비', 'https://www.acmicpc.net/problem/22944', 'BACKTRACKING', 'BOJ', 13),
('색종이 붙이기', 'https://www.acmicpc.net/problem/17136', 'BACKTRACKING', 'BOJ', 14),
('비숍', 'https://www.acmicpc.net/problem/1799', 'BACKTRACKING', 'BOJ', 16);

-- Description: Insert binary_search recommended problems data into the database
Insert into problem (title, url, category, platform, difficulty) VALUES
('수들의 합', 'https://www.acmicpc.net/problem/1789', 'BINARY_SEARCH', 'BOJ', 6),
('숫자 카드', 'https://www.acmicpc.net/problem/10815', 'BINARY_SEARCH', 'BOJ', 6),
('정수 제곱근', 'https://www.acmicpc.net/problem/2417', 'BINARY_SEARCH', 'BOJ', 7),
('IF문 좀 대신 써줘', 'https://www.acmicpc.net/problem/19637', 'BINARY_SEARCH', 'BOJ', 8),
('선분 위의 점', 'https://www.acmicpc.net/problem/11663', 'BINARY_SEARCH', 'BOJ', 8),
('랜선 자르기', 'https://www.acmicpc.net/problem/1654', 'BINARY_SEARCH', 'BOJ', 9),
('나무 자르기', 'https://www.acmicpc.net/problem/2805', 'BINARY_SEARCH', 'BOJ', 9),
('예산', 'https://www.acmicpc.net/problem/2512', 'BINARY_SEARCH', 'BOJ', 9),
('징검다리 건너기 (large)', 'https://www.acmicpc.net/problem/22871', 'BINARY_SEARCH', 'BOJ', 10),
('입국심사', 'https://www.acmicpc.net/problem/3079', 'BINARY_SEARCH', 'BOJ', 11),
('두 용액', 'https://www.acmicpc.net/problem/2470', 'BINARY_SEARCH', 'BOJ', 11),
('색종이와 가위', 'https://www.acmicpc.net/problem/20444', 'BINARY_SEARCH', 'BOJ', 11),
('암벽 등반', 'https://www.acmicpc.net/problem/2412', 'BINARY_SEARCH', 'BOJ', 12),
('휴게소 세우기', 'https://www.acmicpc.net/problem/1477', 'BINARY_SEARCH', 'BOJ', 12),
('공유기 설치', 'https://www.acmicpc.net/problem/2110', 'BINARY_SEARCH', 'BOJ', 12),
('구간 나누기 2', 'https://www.acmicpc.net/problem/13397', 'BINARY_SEARCH', 'BOJ', 12),
('중량제한', 'https://www.acmicpc.net/problem/1939', 'BINARY_SEARCH', 'BOJ', 13),
('세 용액', 'https://www.acmicpc.net/problem/2473', 'BINARY_SEARCH', 'BOJ', 13),
('합이 0인 네 정수', 'https://www.acmicpc.net/problem/7453', 'BINARY_SEARCH', 'BOJ', 14),
('K번째 수', 'https://www.acmicpc.net/problem/1300', 'BINARY_SEARCH', 'BOJ', 15);

-- Description: Insert brute_force recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('시각', 'https://www.acmicpc.net/problem/18312', 'BRUTE_FORCE', 'BOJ', 4),
('피로도', 'https://www.acmicpc.net/problem/22864', 'BRUTE_FORCE', 'BOJ', 4),
('분해합', 'https://www.acmicpc.net/problem/2231', 'BRUTE_FORCE', 'BOJ', 4),
('블랙잭', 'https://www.acmicpc.net/problem/2798', 'BRUTE_FORCE', 'BOJ', 4),
('수학은 비대면강의입니다', 'https://www.acmicpc.net/problem/19532', 'BRUTE_FORCE', 'BOJ', 4),
('큰 수 구성하기', 'https://www.acmicpc.net/problem/18511', 'BRUTE_FORCE', 'BOJ', 6),
('번데기', 'https://www.acmicpc.net/problem/15721', 'BRUTE_FORCE', 'BOJ', 6),
('한윤정이 이탈리아에 가서 아이스크림을 사먹는데', 'https://www.acmicpc.net/problem/2422', 'BRUTE_FORCE', 'BOJ', 7),
('DNA', 'https://www.acmicpc.net/problem/1969', 'BRUTE_FORCE', 'BOJ', 7),
('카드 놓기', 'https://www.acmicpc.net/problem/5568', 'BRUTE_FORCE', 'BOJ', 7),
('치킨치킨치킨', 'https://www.acmicpc.net/problem/16439', 'BRUTE_FORCE', 'BOJ', 7),
('두 스티커', 'https://www.acmicpc.net/problem/16937', 'BRUTE_FORCE', 'BOJ', 8),
('전공책', 'https://www.acmicpc.net/problem/16508', 'BRUTE_FORCE', 'BOJ', 8),
('Four Squares', 'https://www.acmicpc.net/problem/17626', 'BRUTE_FORCE', 'BOJ', 8),
('숫자 야구', 'https://www.acmicpc.net/problem/2503', 'BRUTE_FORCE', 'BOJ', 8),
('퇴사', 'https://www.acmicpc.net/problem/14501', 'BRUTE_FORCE', 'BOJ', 8),
('꽃길', 'https://www.acmicpc.net/problem/14620', 'BRUTE_FORCE', 'BOJ', 9),
('도영이가 만든 맛있는 음식', 'https://www.acmicpc.net/problem/2961', 'BRUTE_FORCE', 'BOJ', 9),
('동전 게임', 'https://www.acmicpc.net/problem/9079', 'BRUTE_FORCE', 'BOJ', 9),
('오목', 'https://www.acmicpc.net/problem/2615', 'BRUTE_FORCE', 'BOJ', 10),
('A와 B 2', 'https://www.acmicpc.net/problem/12919', 'BRUTE_FORCE', 'BOJ', 11),
('제곱수 찾기', 'https://www.acmicpc.net/problem/1025', 'BRUTE_FORCE', 'BOJ', 11),
('부분 삼각 수열', 'https://www.acmicpc.net/problem/1548', 'BRUTE_FORCE', 'BOJ', 11),
('링크와 스타트', 'https://www.acmicpc.net/problem/15661', 'BRUTE_FORCE', 'BOJ', 11),
('카드 섞기', 'https://www.acmicpc.net/problem/21315', 'BRUTE_FORCE', 'BOJ', 11),
('치킨 배달', 'https://www.acmicpc.net/problem/15686', 'BRUTE_FORCE', 'BOJ', 11),
('테트로미노', 'https://www.acmicpc.net/problem/14500', 'BRUTE_FORCE', 'BOJ', 12),
('호석이 두 마리 치킨', 'https://www.acmicpc.net/problem/21278', 'BRUTE_FORCE', 'BOJ', 12),
('죽음의 비', 'https://www.acmicpc.net/problem/22944', 'BRUTE_FORCE', 'BOJ', 13),
('괄호 추가하기', 'https://www.acmicpc.net/problem/16637', 'BRUTE_FORCE', 'BOJ', 13),
('종이 조각', 'https://www.acmicpc.net/problem/14391', 'BRUTE_FORCE', 'BOJ', 13),
('스티커 붙이기', 'https://www.acmicpc.net/problem/18808', 'BRUTE_FORCE', 'BOJ', 13),
('연산 최대로', 'https://www.acmicpc.net/problem/21943', 'BRUTE_FORCE', 'BOJ', 14);

-- Description: Insert data_structure recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('큐 2', 'https://www.acmicpc.net/problem/18258', 'DATA_STRUCTURE', 'BOJ', 7),
('스택', 'https://www.acmicpc.net/problem/10828', 'DATA_STRUCTURE', 'BOJ', 7),
('괄호', 'https://www.acmicpc.net/problem/9012', 'DATA_STRUCTURE', 'BOJ', 7),
('요세푸스 문제', 'https://www.acmicpc.net/problem/1158', 'DATA_STRUCTURE', 'BOJ', 7),
('카드2', 'https://www.acmicpc.net/problem/2164', 'DATA_STRUCTURE', 'BOJ', 7),
('덱', 'https://www.acmicpc.net/problem/10866', 'DATA_STRUCTURE', 'BOJ', 7),
('풍선 터뜨리기', 'https://www.acmicpc.net/problem/2346', 'DATA_STRUCTURE', 'BOJ', 8),
('후위 표기식2', 'https://www.acmicpc.net/problem/1935', 'DATA_STRUCTURE', 'BOJ', 8),
('프린터 큐', 'https://www.acmicpc.net/problem/1966', 'DATA_STRUCTURE', 'BOJ', 8),
('스택 수열', 'https://www.acmicpc.net/problem/1874', 'DATA_STRUCTURE', 'BOJ', 9),
('쇠막대기', 'https://www.acmicpc.net/problem/10799', 'DATA_STRUCTURE', 'BOJ', 9),
('괄호의 값', 'https://www.acmicpc.net/problem/2504', 'DATA_STRUCTURE', 'BOJ', 11),
('탑', 'https://www.acmicpc.net/problem/2493', 'DATA_STRUCTURE', 'BOJ', 11),
('데이터 체커', 'https://www.acmicpc.net/problem/22942', 'DATA_STRUCTURE', 'BOJ', 12),
('괄호 제거', 'https://www.acmicpc.net/problem/2800', 'DATA_STRUCTURE', 'BOJ', 12),
('후위 표기식', 'https://www.acmicpc.net/problem/1918', 'DATA_STRUCTURE', 'BOJ', 14),
('나는야 포켓몬 마스터 이다솜', 'https://www.acmicpc.net/problem/1620', 'DATA_STRUCTURE', 'BOJ', 7),
('문자열 집합', 'https://www.acmicpc.net/problem/14425', 'DATA_STRUCTURE', 'BOJ', 7),
('N번째 큰 수', 'https://www.acmicpc.net/problem/2075', 'DATA_STRUCTURE', 'BOJ', 8),
('생태학', 'https://www.acmicpc.net/problem/4358', 'DATA_STRUCTURE', 'BOJ', 9),
('최대 힙', 'https://www.acmicpc.net/problem/11279', 'DATA_STRUCTURE', 'BOJ', 9),
('절댓값 힙', 'https://www.acmicpc.net/problem/11286', 'DATA_STRUCTURE', 'BOJ', 10),
('이중 우선순위 큐', 'https://www.acmicpc.net/problem/7662', 'DATA_STRUCTURE', 'BOJ', 12),
('문제 추천 시스템 Version 1', 'https://www.acmicpc.net/problem/21939', 'DATA_STRUCTURE', 'BOJ', 12),
('부품 대여장', 'https://www.acmicpc.net/problem/21942', 'DATA_STRUCTURE', 'BOJ', 14),
('문제 추천 시스템 Version 2', 'https://www.acmicpc.net/problem/21944', 'DATA_STRUCTURE', 'BOJ', 14),
('중앙값 구하기', 'https://www.acmicpc.net/problem/2696', 'DATA_STRUCTURE', 'BOJ', 14);

-- Description: Insert disjoint_set recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('집합의 표현', 'https://www.acmicpc.net/problem/1717', 'DISJOINT_SET', 'BOJ', 11),
('로봇 조립', 'https://www.acmicpc.net/problem/18116', 'DISJOINT_SET', 'BOJ', 12),
('여행 가자', 'https://www.acmicpc.net/problem/1976', 'DISJOINT_SET', 'BOJ', 12),
('친구비', 'https://www.acmicpc.net/problem/16562', 'DISJOINT_SET', 'BOJ', 12),
('친구 네트워크', 'https://www.acmicpc.net/problem/4195', 'DISJOINT_SET', 'BOJ', 14),
('공항', 'https://www.acmicpc.net/problem/10775', 'DISJOINT_SET', 'BOJ', 14);

-- Description: Insert divide_and_conquer recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('투에-모스 문자열', 'https://www.acmicpc.net/problem/18222', 'DIVIDE_AND_CONQUER', 'BOJ', 9),
('색종이 만들기', 'https://www.acmicpc.net/problem/2630', 'DIVIDE_AND_CONQUER', 'BOJ', 9),
('222-풀링', 'https://www.acmicpc.net/problem/17829', 'DIVIDE_AND_CONQUER', 'BOJ', 9),
('쿼드트리', 'https://www.acmicpc.net/problem/1992', 'DIVIDE_AND_CONQUER', 'BOJ', 10),
('Z', 'https://www.acmicpc.net/problem/1074', 'DIVIDE_AND_CONQUER', 'BOJ', 11),
('별 찍기 - 10', 'https://www.acmicpc.net/problem/2447', 'DIVIDE_AND_CONQUER', 'BOJ', 11),
('별 찍기 - 11', 'https://www.acmicpc.net/problem/2448', 'DIVIDE_AND_CONQUER', 'BOJ', 12),
('트리', 'https://www.acmicpc.net/problem/4256', 'DIVIDE_AND_CONQUER', 'BOJ', 14);

-- Description: Insert dynamic_programming recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('피보나치 수 5', 'https://www.acmicpc.net/problem/10870', 'DYNAMIC_PROGRAMMING', 'BOJ', 4),
('피보나치 수 2', 'https://www.acmicpc.net/problem/2748', 'DYNAMIC_PROGRAMMING', 'BOJ', 5),
('다리 놓기', 'https://www.acmicpc.net/problem/1010', 'DYNAMIC_PROGRAMMING', 'BOJ', 6),
('돌 게임', 'https://www.acmicpc.net/problem/9655', 'DYNAMIC_PROGRAMMING', 'BOJ', 6),
('설탕 배달', 'https://www.acmicpc.net/problem/2839', 'DYNAMIC_PROGRAMMING', 'BOJ', 7),
('1로 만들기', 'https://www.acmicpc.net/problem/1463', 'DYNAMIC_PROGRAMMING', 'BOJ', 8),
('계단 오르기', 'https://www.acmicpc.net/problem/2579', 'DYNAMIC_PROGRAMMING', 'BOJ', 8),
('2×n 타일링', 'https://www.acmicpc.net/problem/11726', 'DYNAMIC_PROGRAMMING', 'BOJ', 8),
('조합', 'https://www.acmicpc.net/problem/2407', 'DYNAMIC_PROGRAMMING', 'BOJ', 8),
('Four Squares', 'https://www.acmicpc.net/problem/17626', 'DYNAMIC_PROGRAMMING', 'BOJ', 8),
('2×n 타일링 2', 'https://www.acmicpc.net/problem/11727', 'DYNAMIC_PROGRAMMING', 'BOJ', 8),
('1, 2, 3 더하기', 'https://www.acmicpc.net/problem/9095', 'DYNAMIC_PROGRAMMING', 'BOJ', 8),
('연속합', 'https://www.acmicpc.net/problem/1912', 'DYNAMIC_PROGRAMMING', 'BOJ', 9),
('가장 긴 증가하는 부분 수열', 'https://www.acmicpc.net/problem/11053', 'DYNAMIC_PROGRAMMING', 'BOJ', 9),
('가장 긴 짝수 연속한 부분 수열 (small)', 'https://www.acmicpc.net/problem/22857', 'DYNAMIC_PROGRAMMING', 'BOJ', 9),
('가장 큰 증가하는 부분 수열', 'https://www.acmicpc.net/problem/11055', 'DYNAMIC_PROGRAMMING', 'BOJ', 9),
('징검다리 건너기', 'https://www.acmicpc.net/problem/21317', 'DYNAMIC_PROGRAMMING', 'BOJ', 10),
('쉬운 계단 수', 'https://www.acmicpc.net/problem/10844', 'DYNAMIC_PROGRAMMING', 'BOJ', 10),
('점프', 'https://www.acmicpc.net/problem/1890', 'DYNAMIC_PROGRAMMING', 'BOJ', 10),
('포도주 시식', 'https://www.acmicpc.net/problem/2156', 'DYNAMIC_PROGRAMMING', 'BOJ', 10),
('징검다리 건너기 (small)', 'https://www.acmicpc.net/problem/22869', 'DYNAMIC_PROGRAMMING', 'BOJ', 10),
('구간 합 구하기 5', 'https://www.acmicpc.net/problem/11660', 'DYNAMIC_PROGRAMMING', 'BOJ', 10),
('스티커', 'https://www.acmicpc.net/problem/9465', 'DYNAMIC_PROGRAMMING', 'BOJ', 10),
('동전 2', 'https://www.acmicpc.net/problem/2294', 'DYNAMIC_PROGRAMMING', 'BOJ', 11),
('퇴사 2', 'https://www.acmicpc.net/problem/15486', 'DYNAMIC_PROGRAMMING', 'BOJ', 11),
('호텔', 'https://www.acmicpc.net/problem/1106', 'DYNAMIC_PROGRAMMING', 'BOJ', 12),
('동전 1', 'https://www.acmicpc.net/problem/2293', 'DYNAMIC_PROGRAMMING', 'BOJ', 12),
('주지수', 'https://www.acmicpc.net/problem/15724', 'DYNAMIC_PROGRAMMING', 'BOJ', 10),
('평범한 배낭', 'https://www.acmicpc.net/problem/12865', 'DYNAMIC_PROGRAMMING', 'BOJ', 11),
('LCS', 'https://www.acmicpc.net/problem/9251', 'DYNAMIC_PROGRAMMING', 'BOJ', 11),
('합분해', 'https://www.acmicpc.net/problem/2225', 'DYNAMIC_PROGRAMMING', 'BOJ', 11),
('1학년', 'https://www.acmicpc.net/problem/5557', 'DYNAMIC_PROGRAMMING', 'BOJ', 11),
('진우의 달 여행 (Large)', 'https://www.acmicpc.net/problem/17485', 'DYNAMIC_PROGRAMMING', 'BOJ', 11),
('선수과목 (Prerequisite)', 'https://www.acmicpc.net/problem/14567', 'DYNAMIC_PROGRAMMING', 'BOJ', 11),
('동전', 'https://www.acmicpc.net/problem/9084', 'DYNAMIC_PROGRAMMING', 'BOJ', 11),
('로또', 'https://www.acmicpc.net/problem/2758', 'DYNAMIC_PROGRAMMING', 'BOJ', 12),
('가장 큰 정사각형', 'https://www.acmicpc.net/problem/1915', 'DYNAMIC_PROGRAMMING', 'BOJ', 12),
('팰린드롬?', 'https://www.acmicpc.net/problem/10942', 'DYNAMIC_PROGRAMMING', 'BOJ', 12),
('수도배관공사', 'https://www.acmicpc.net/problem/2073', 'DYNAMIC_PROGRAMMING', 'BOJ', 12),
('함께 블록 쌓기', 'https://www.acmicpc.net/problem/18427', 'DYNAMIC_PROGRAMMING', 'BOJ', 12),
('작업', 'https://www.acmicpc.net/problem/2056', 'DYNAMIC_PROGRAMMING', 'BOJ', 12),
('문자열 제거', 'https://www.acmicpc.net/problem/21941', 'DYNAMIC_PROGRAMMING', 'BOJ', 12),
('곡예 비행', 'https://www.acmicpc.net/problem/21923', 'DYNAMIC_PROGRAMMING', 'BOJ', 12),
('동전 바꿔주기', 'https://www.acmicpc.net/problem/2624', 'DYNAMIC_PROGRAMMING', 'BOJ', 12),
('줄세우기', 'https://www.acmicpc.net/problem/2631', 'DYNAMIC_PROGRAMMING', 'BOJ', 12),
('내리막 길', 'https://www.acmicpc.net/problem/1520', 'DYNAMIC_PROGRAMMING', 'BOJ', 13),
('구간 나누기', 'https://www.acmicpc.net/problem/2228', 'DYNAMIC_PROGRAMMING', 'BOJ', 13),
('ACM Craft', 'https://www.acmicpc.net/problem/1005', 'DYNAMIC_PROGRAMMING', 'BOJ', 13),
('양팔저울', 'https://www.acmicpc.net/problem/2629', 'DYNAMIC_PROGRAMMING', 'BOJ', 13),
('팰린드롬 만들기', 'https://www.acmicpc.net/problem/1695', 'DYNAMIC_PROGRAMMING', 'BOJ', 13),
('행렬 곱셈 순서', 'https://www.acmicpc.net/problem/11049', 'DYNAMIC_PROGRAMMING', 'BOJ', 13),
('수확', 'https://www.acmicpc.net/problem/1823', 'DYNAMIC_PROGRAMMING', 'BOJ', 13),
('받아쓰기', 'https://www.acmicpc.net/problem/20542', 'DYNAMIC_PROGRAMMING', 'BOJ', 13),
('성냥개비', 'https://www.acmicpc.net/problem/3687', 'DYNAMIC_PROGRAMMING', 'BOJ', 14),
('꿈틀꿈틀 호석 애벌레 - 효율성', 'https://www.acmicpc.net/problem/20181', 'DYNAMIC_PROGRAMMING', 'BOJ', 14),
('트리와 쿼리', 'https://www.acmicpc.net/problem/15681', 'DYNAMIC_PROGRAMMING', 'BOJ', 11),
('사회망 서비스(SNS)', 'https://www.acmicpc.net/problem/2533', 'DYNAMIC_PROGRAMMING', 'BOJ', 13),
('우수 마을', 'https://www.acmicpc.net/problem/1949', 'DYNAMIC_PROGRAMMING', 'BOJ', 14),
('트리의 독립집합', 'https://www.acmicpc.net/problem/2213', 'DYNAMIC_PROGRAMMING', 'BOJ', 15);

-- Description: Insert graph_traversal recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('바이러스', 'https://www.acmicpc.net/problem/2606', 'GRAPH_TRAVERSAL', 'BOJ', 8),
('DFS와 BFS', 'https://www.acmicpc.net/problem/1260', 'GRAPH_TRAVERSAL', 'BOJ', 9),
('트리의 부모 찾기', 'https://www.acmicpc.net/problem/11725', 'GRAPH_TRAVERSAL', 'BOJ', 9),
('효율적인 해킹', 'https://www.acmicpc.net/problem/1325', 'GRAPH_TRAVERSAL', 'BOJ', 10),
('쉬운 최단거리', 'https://www.acmicpc.net/problem/14940', 'GRAPH_TRAVERSAL', 'BOJ', 10),
('봄버맨', 'https://www.acmicpc.net/problem/16918', 'GRAPH_TRAVERSAL', 'BOJ', 10),
('단지번호붙이기', 'https://www.acmicpc.net/problem/2667', 'GRAPH_TRAVERSAL', 'BOJ', 10),
('미로 탐색', 'https://www.acmicpc.net/problem/2178', 'GRAPH_TRAVERSAL', 'BOJ', 10),
('숨바꼭질 3', 'https://www.acmicpc.net/problem/13549', 'GRAPH_TRAVERSAL', 'BOJ', 11),
('공주님을 구해라!', 'https://www.acmicpc.net/problem/17836', 'GRAPH_TRAVERSAL', 'BOJ', 11),
('ABCDE', 'https://www.acmicpc.net/problem/13023', 'GRAPH_TRAVERSAL', 'BOJ', 11),
('토마토', 'https://www.acmicpc.net/problem/7576', 'GRAPH_TRAVERSAL', 'BOJ', 11),
('토마토', 'https://www.acmicpc.net/problem/7569', 'GRAPH_TRAVERSAL', 'BOJ', 11),
('숫자고르기', 'https://www.acmicpc.net/problem/2668', 'GRAPH_TRAVERSAL', 'BOJ', 11),
('샘터', 'https://www.acmicpc.net/problem/18513', 'GRAPH_TRAVERSAL', 'BOJ', 12),
('빙산', 'https://www.acmicpc.net/problem/2573', 'GRAPH_TRAVERSAL', 'BOJ', 12),
('직사각형 탈출', 'https://www.acmicpc.net/problem/16973', 'GRAPH_TRAVERSAL', 'BOJ', 12),
('인구 이동', 'https://www.acmicpc.net/problem/16234', 'GRAPH_TRAVERSAL', 'BOJ', 12),
('트리의 지름', 'https://www.acmicpc.net/problem/1967', 'GRAPH_TRAVERSAL', 'BOJ', 12),
('연구소', 'https://www.acmicpc.net/problem/14502', 'GRAPH_TRAVERSAL', 'BOJ', 12),
('치즈', 'https://www.acmicpc.net/problem/2636', 'GRAPH_TRAVERSAL', 'BOJ', 12),
('일루미네이션', 'https://www.acmicpc.net/problem/5547', 'GRAPH_TRAVERSAL', 'BOJ', 12),
('불!', 'https://www.acmicpc.net/problem/4179', 'GRAPH_TRAVERSAL', 'BOJ', 13),
('말이 되고픈 원숭이', 'https://www.acmicpc.net/problem/1600', 'GRAPH_TRAVERSAL', 'BOJ', 13),
('벽 부수고 이동하기', 'https://www.acmicpc.net/problem/2206', 'GRAPH_TRAVERSAL', 'BOJ', 13),
('텀 프로젝트', 'https://www.acmicpc.net/problem/9466', 'GRAPH_TRAVERSAL', 'BOJ', 13),
('산책 (small)', 'https://www.acmicpc.net/problem/22868', 'GRAPH_TRAVERSAL', 'BOJ', 13),
('움직이는 미로 탈출', 'https://www.acmicpc.net/problem/16954', 'GRAPH_TRAVERSAL', 'BOJ', 13),
('모양 만들기', 'https://www.acmicpc.net/problem/16932', 'GRAPH_TRAVERSAL', 'BOJ', 13),
('원 이동하기 1', 'https://www.acmicpc.net/problem/22946', 'GRAPH_TRAVERSAL', 'BOJ', 14),
('원 이동하기 2', 'https://www.acmicpc.net/problem/22948', 'GRAPH_TRAVERSAL', 'BOJ', 14);

-- Description: Insert greedy recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('거스름돈', 'https://www.acmicpc.net/problem/14916', 'GREEDY', 'BOJ', 6),
('폴리오미노', 'https://www.acmicpc.net/problem/1343', 'GREEDY', 'BOJ', 6),
('로프', 'https://www.acmicpc.net/problem/2217', 'GREEDY', 'BOJ', 7),
('알바생 강호', 'https://www.acmicpc.net/problem/1758', 'GREEDY', 'BOJ', 7),
('동전 0', 'https://www.acmicpc.net/problem/11047', 'GREEDY', 'BOJ', 7),
('2+1 세일', 'https://www.acmicpc.net/problem/11508', 'GREEDY', 'BOJ', 7),
('ATM', 'https://www.acmicpc.net/problem/11399', 'GREEDY', 'BOJ', 7),
('서강근육맨', 'https://www.acmicpc.net/problem/20300', 'GREEDY', 'BOJ', 8),
('주유소', 'https://www.acmicpc.net/problem/13305', 'GREEDY', 'BOJ', 8),
('블로그2', 'https://www.acmicpc.net/problem/20365', 'GREEDY', 'BOJ', 8),
('에너지 드링크', 'https://www.acmicpc.net/problem/20115', 'GREEDY', 'BOJ', 8),
('A → B', 'https://www.acmicpc.net/problem/16953', 'GREEDY', 'BOJ', 9),
('잃어버린 괄호', 'https://www.acmicpc.net/problem/1541', 'GREEDY', 'BOJ', 9),
('민겸 수', 'https://www.acmicpc.net/problem/21314', 'GREEDY', 'BOJ', 10),
('배', 'https://www.acmicpc.net/problem/1092', 'GREEDY', 'BOJ', 11),
('강의실 배정', 'https://www.acmicpc.net/problem/11000', 'GREEDY', 'BOJ', 11),
('회의실 배정', 'https://www.acmicpc.net/problem/1931', 'GREEDY', 'BOJ', 11),
('꿀 따기', 'https://www.acmicpc.net/problem/21758', 'GREEDY', 'BOJ', 11),
('최소 회의실 개수', 'https://www.acmicpc.net/problem/19598', 'GREEDY', 'BOJ', 11),
('센서', 'https://www.acmicpc.net/problem/2212', 'GREEDY', 'BOJ', 11),
('행복 유치원', 'https://www.acmicpc.net/problem/13164', 'GREEDY', 'BOJ', 11),
('우체국', 'https://www.acmicpc.net/problem/2141', 'GREEDY', 'BOJ', 12),
('우체국', 'https://www.acmicpc.net/problem/2285', 'GREEDY', 'BOJ', 12),
('카드 정렬하기', 'https://www.acmicpc.net/problem/1715', 'GREEDY', 'BOJ', 12),
('파일 합치기 3', 'https://www.acmicpc.net/problem/13975', 'GREEDY', 'BOJ', 12),
('크게 만들기', 'https://www.acmicpc.net/problem/2812', 'GREEDY', 'BOJ', 13),
('택배', 'https://www.acmicpc.net/problem/8980', 'GREEDY', 'BOJ', 15);

-- Description: Insert implementation recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('윤년', 'https://www.acmicpc.net/problem/2753', 'IMPLEMENTATION', 'BOJ', 1),
('과제 안 내신 분..?', 'https://www.acmicpc.net/problem/5597', 'IMPLEMENTATION', 'BOJ', 3),
('최소, 최대 2', 'https://www.acmicpc.net/problem/20053', 'IMPLEMENTATION', 'BOJ', 3),
('8진수 2진수', 'https://www.acmicpc.net/problem/1212', 'IMPLEMENTATION', 'BOJ', 4),
('전구', 'https://www.acmicpc.net/problem/21918', 'IMPLEMENTATION', 'BOJ', 4),
('소가 길을 건너간 이유 1', 'https://www.acmicpc.net/problem/14467', 'IMPLEMENTATION', 'BOJ', 5),
('🐜 기적의 매매법 🐜', 'https://www.acmicpc.net/problem/20546', 'IMPLEMENTATION', 'BOJ', 6),
('스위치 켜고 끄기', 'https://www.acmicpc.net/problem/1244', 'IMPLEMENTATION', 'BOJ', 7),
('지뢰 찾기', 'https://www.acmicpc.net/problem/4396', 'IMPLEMENTATION', 'BOJ', 7),
('빙고', 'https://www.acmicpc.net/problem/2578', 'IMPLEMENTATION', 'BOJ', 7),
('ZOAC 3', 'https://www.acmicpc.net/problem/20436', 'IMPLEMENTATION', 'BOJ', 7),
('별 찍기 - 19', 'https://www.acmicpc.net/problem/10994', 'IMPLEMENTATION', 'BOJ', 7),
('달팽이', 'https://www.acmicpc.net/problem/1913', 'IMPLEMENTATION', 'BOJ', 8),
('단어 뒤집기 2', 'https://www.acmicpc.net/problem/17413', 'IMPLEMENTATION', 'BOJ', 8),
('원상 복구 (small)', 'https://www.acmicpc.net/problem/22858', 'IMPLEMENTATION', 'BOJ', 8),
('파일 정리', 'https://www.acmicpc.net/problem/20291', 'IMPLEMENTATION', 'BOJ', 8),
('기차가 어둠을 헤치고 은하수를', 'https://www.acmicpc.net/problem/15787', 'IMPLEMENTATION', 'BOJ', 9),
('오리', 'https://www.acmicpc.net/problem/12933', 'IMPLEMENTATION', 'BOJ', 9),
('오목', 'https://www.acmicpc.net/problem/2615', 'IMPLEMENTATION', 'BOJ', 10),
('배열 돌리기', 'https://www.acmicpc.net/problem/17276', 'IMPLEMENTATION', 'BOJ', 10),
('달력', 'https://www.acmicpc.net/problem/20207', 'IMPLEMENTATION', 'BOJ', 11),
('배열 돌리기 1', 'https://www.acmicpc.net/problem/16926', 'IMPLEMENTATION', 'BOJ', 11),
('ZOAC', 'https://www.acmicpc.net/problem/16719', 'IMPLEMENTATION', 'BOJ', 11),
('빗물', 'https://www.acmicpc.net/problem/14719', 'IMPLEMENTATION', 'BOJ', 11),
('홀수 홀릭 호석', 'https://www.acmicpc.net/problem/20164', 'IMPLEMENTATION', 'BOJ', 11),
('트리 순회', 'https://www.acmicpc.net/problem/22856', 'IMPLEMENTATION', 'BOJ', 12),
('HTML 파싱', 'https://www.acmicpc.net/problem/22859', 'IMPLEMENTATION', 'BOJ', 13),
('폴더 정리 (small)', 'https://www.acmicpc.net/problem/22860', 'IMPLEMENTATION', 'BOJ', 13);

-- Description: Insert math recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('소수', 'https://www.acmicpc.net/problem/2581', 'MATH', 'BOJ', 4),
('피로도', 'https://www.acmicpc.net/problem/22864', 'MATH', 'BOJ', 4),
('소수 찾기', 'https://www.acmicpc.net/problem/1978', 'MATH', 'BOJ', 4),
('진법 변환', 'https://www.acmicpc.net/problem/2745', 'MATH', 'BOJ', 4),
('공약수', 'https://www.acmicpc.net/problem/5618', 'MATH', 'BOJ', 4),
('더하기 사이클', 'https://www.acmicpc.net/problem/1110', 'MATH', 'BOJ', 5),
('소인수분해', 'https://www.acmicpc.net/problem/11653', 'MATH', 'BOJ', 5),
('최소공배수', 'https://www.acmicpc.net/problem/1934', 'MATH', 'BOJ', 5),
('최대공약수와 최소공배수', 'https://www.acmicpc.net/problem/2609', 'MATH', 'BOJ', 5),
('LCM', 'https://www.acmicpc.net/problem/5347', 'MATH', 'BOJ', 6),
('다음 소수', 'https://www.acmicpc.net/problem/4134', 'MATH', 'BOJ', 7),
('서로소 평균', 'https://www.acmicpc.net/problem/21920', 'MATH', 'BOJ', 7),
('GCD 합', 'https://www.acmicpc.net/problem/9613', 'MATH', 'BOJ', 7),
('에라토스테네스의 체', 'https://www.acmicpc.net/problem/2960', 'MATH', 'BOJ', 7),
('소수 최소 공배수', 'https://www.acmicpc.net/problem/21919', 'MATH', 'BOJ', 8),
('폰 호석만', 'https://www.acmicpc.net/problem/21275', 'MATH', 'BOJ', 9),
('소수&팰린드롬', 'https://www.acmicpc.net/problem/1747', 'MATH', 'BOJ', 10),
('수', 'https://www.acmicpc.net/problem/22943', 'MATH', 'BOJ', 11);

-- Description: Insert minimum_spanning_tree recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('최소 스패닝 트리', 'https://www.acmicpc.net/problem/1197', 'MINIMUM_SPANNING_TREE', 'BOJ', 12),
('도시 건설', 'https://www.acmicpc.net/problem/21924', 'MINIMUM_SPANNING_TREE', 'BOJ', 12),
('행성 연결', 'https://www.acmicpc.net/problem/16398', 'MINIMUM_SPANNING_TREE', 'BOJ', 12),
('도시 분할 계획', 'https://www.acmicpc.net/problem/1647', 'MINIMUM_SPANNING_TREE', 'BOJ', 12),
('네트워크 연결', 'https://www.acmicpc.net/problem/1922', 'MINIMUM_SPANNING_TREE', 'BOJ', 12),
('우주신과의 교감', 'https://www.acmicpc.net/problem/1774', 'MINIMUM_SPANNING_TREE', 'BOJ', 13),
('나만 안되는 연애', 'https://www.acmicpc.net/problem/14621', 'MINIMUM_SPANNING_TREE', 'BOJ', 13),
('물대기', 'https://www.acmicpc.net/problem/1368', 'MINIMUM_SPANNING_TREE', 'BOJ', 14);

-- Description: Insert prefix_sum recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('귀찮아 (SIB)', 'https://www.acmicpc.net/problem/14929', 'PREFIX_SUM', 'BOJ', 6),
('2차원 배열의 합', 'https://www.acmicpc.net/problem/2167', 'PREFIX_SUM', 'BOJ', 6),
('출석체크', 'https://www.acmicpc.net/problem/20438', 'PREFIX_SUM', 'BOJ', 9),
('구간 합 구하기 5', 'https://www.acmicpc.net/problem/11660', 'PREFIX_SUM', 'BOJ', 10),
('피아노 체조', 'https://www.acmicpc.net/problem/21318', 'PREFIX_SUM', 'BOJ', 10),
('점수따먹기', 'https://www.acmicpc.net/problem/1749', 'PREFIX_SUM', 'BOJ', 12),
('수들의 합 4', 'https://www.acmicpc.net/problem/2015', 'PREFIX_SUM', 'BOJ', 12),
('나머지 합', 'https://www.acmicpc.net/problem/10986', 'PREFIX_SUM', 'BOJ', 13),
('🎵니가 싫어 싫어 너무 싫어 싫어 오지 마 내게 찝쩍대지마🎵 - 1', 'https://www.acmicpc.net/problem/20440', 'PREFIX_SUM', 'BOJ', 13),
('나누기', 'https://www.acmicpc.net/problem/21757', 'PREFIX_SUM', 'BOJ', 14),
('폭탄 던지는 태영이', 'https://www.acmicpc.net/problem/20543', 'PREFIX_SUM', 'BOJ', 15);

-- Description: Insert shortest_path recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('특정 거리의 도시 찾기', 'https://www.acmicpc.net/problem/18352', 'SHORTEST_PATH', 'BOJ', 9),
('경로 찾기', 'https://www.acmicpc.net/problem/11403', 'SHORTEST_PATH', 'BOJ', 10),
('숨바꼭질 3', 'https://www.acmicpc.net/problem/13549', 'SHORTEST_PATH', 'BOJ', 11),
('타임머신', 'https://www.acmicpc.net/problem/11657', 'SHORTEST_PATH', 'BOJ', 12),
('최단경로', 'https://www.acmicpc.net/problem/1753', 'SHORTEST_PATH', 'BOJ', 12),
('발전소 설치', 'https://www.acmicpc.net/problem/1277', 'SHORTEST_PATH', 'BOJ', 12),
('명제 증명', 'https://www.acmicpc.net/problem/2224', 'SHORTEST_PATH', 'BOJ', 12),
('운동', 'https://www.acmicpc.net/problem/1956', 'SHORTEST_PATH', 'BOJ', 12),
('가장 먼 곳', 'https://www.acmicpc.net/problem/22865', 'SHORTEST_PATH', 'BOJ', 12),
('플로이드', 'https://www.acmicpc.net/problem/11404', 'SHORTEST_PATH', 'BOJ', 12),
('끝나지 않는 파티', 'https://www.acmicpc.net/problem/11265', 'SHORTEST_PATH', 'BOJ', 12),
('서강그라운드', 'https://www.acmicpc.net/problem/14938', 'SHORTEST_PATH', 'BOJ', 12),
('저울', 'https://www.acmicpc.net/problem/10159', 'SHORTEST_PATH', 'BOJ', 12),
('웜홀', 'https://www.acmicpc.net/problem/1865', 'SHORTEST_PATH', 'BOJ', 13),
('역사', 'https://www.acmicpc.net/problem/1613', 'SHORTEST_PATH', 'BOJ', 13),
('파티', 'https://www.acmicpc.net/problem/1238', 'SHORTEST_PATH', 'BOJ', 13),
('택배', 'https://www.acmicpc.net/problem/1719', 'SHORTEST_PATH', 'BOJ', 13),
('궁금한 민호', 'https://www.acmicpc.net/problem/1507', 'SHORTEST_PATH', 'BOJ', 14);

-- Description: Insert simulation recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('ZOAC 3', 'https://www.acmicpc.net/problem/20436', 'SIMULATION', 'BOJ', 7),
('지구 온난화', 'https://www.acmicpc.net/problem/5212', 'SIMULATION', 'BOJ', 9),
('후보 추천하기', 'https://www.acmicpc.net/problem/1713', 'SIMULATION', 'BOJ', 10),
('학부 연구생 민상', 'https://www.acmicpc.net/problem/21922', 'SIMULATION', 'BOJ', 11),
('인내의 도미노 장인 호석', 'https://www.acmicpc.net/problem/20165', 'SIMULATION', 'BOJ', 11),
('톱니바퀴', 'https://www.acmicpc.net/problem/14891', 'SIMULATION', 'BOJ', 11),
('컨베이어 벨트 위의 로봇', 'https://www.acmicpc.net/problem/20055', 'SIMULATION', 'BOJ', 11),
('감시', 'https://www.acmicpc.net/problem/15683', 'SIMULATION', 'BOJ', 13),
('새로운 게임 2', 'https://www.acmicpc.net/problem/17837', 'SIMULATION', 'BOJ', 14),
('폴더 정리 (large)', 'https://www.acmicpc.net/problem/22861', 'SIMULATION', 'BOJ', 15),
('구슬 탈출 2', 'https://www.acmicpc.net/problem/13460', 'SIMULATION', 'BOJ', 15);

-- Description: Insert string recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('숫자의 합', 'https://www.acmicpc.net/problem/11720', 'STRING', 'BOJ', 2),
('!밀비 급일', 'https://www.acmicpc.net/problem/11365', 'STRING', 'BOJ', 2),
('경고', 'https://www.acmicpc.net/problem/3029', 'STRING', 'BOJ', 3),
('부분 문자열', 'https://www.acmicpc.net/problem/16916', 'STRING', 'BOJ', 4),
('복호화', 'https://www.acmicpc.net/problem/9046', 'STRING', 'BOJ', 4),
('나는 친구가 적다 (Small)', 'https://www.acmicpc.net/problem/16171', 'STRING', 'BOJ', 4),
('세로읽기', 'https://www.acmicpc.net/problem/10798', 'STRING', 'BOJ', 5),
('이 구역의 승자는 누구야?!', 'https://www.acmicpc.net/problem/20154', 'STRING', 'BOJ', 5),
('부분 문자열', 'https://www.acmicpc.net/problem/6550', 'STRING', 'BOJ', 6),
('단어 정렬', 'https://www.acmicpc.net/problem/1181', 'STRING', 'BOJ', 6),
('비밀번호 발음하기', 'https://www.acmicpc.net/problem/4659', 'STRING', 'BOJ', 6),
('그룹 단어 체커', 'https://www.acmicpc.net/problem/1316', 'STRING', 'BOJ', 6),
('듣보잡', 'https://www.acmicpc.net/problem/1764', 'STRING', 'BOJ', 7),
('단어 뒤집기 2', 'https://www.acmicpc.net/problem/17413', 'STRING', 'BOJ', 8),
('파일 정리', 'https://www.acmicpc.net/problem/20291', 'STRING', 'BOJ', 8),
('염색체', 'https://www.acmicpc.net/problem/9342', 'STRING', 'BOJ', 8),
('회문', 'https://www.acmicpc.net/problem/17609', 'STRING', 'BOJ', 11),
('문자열 게임 2', 'https://www.acmicpc.net/problem/20437', 'STRING', 'BOJ', 11),
('파일 탐색기', 'https://www.acmicpc.net/problem/20210', 'STRING', 'BOJ', 13);

-- Description: Insert topological_sorting recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('선수과목 (Prerequisite)', 'https://www.acmicpc.net/problem/14567', 'TOPOLOGICAL_SORT', 'BOJ', 11),
('ACM Craft', 'https://www.acmicpc.net/problem/1005', 'TOPOLOGICAL_SORT', 'BOJ', 13),
('음악프로그램', 'https://www.acmicpc.net/problem/2623', 'TOPOLOGICAL_SORT', 'BOJ', 13),
('줄 세우기', 'https://www.acmicpc.net/problem/2252', 'TOPOLOGICAL_SORT', 'BOJ', 13),
('문제집', 'https://www.acmicpc.net/problem/1766', 'TOPOLOGICAL_SORT', 'BOJ', 14);

-- Description: Insert tree recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('트리인가?', 'https://www.acmicpc.net/problem/6416', 'TREE', 'BOJ', 0),
('트리의 부모 찾기', 'https://www.acmicpc.net/problem/11725', 'TREE', 'BOJ', 9),
('단절점과 단절선', 'https://www.acmicpc.net/problem/14675', 'TREE', 'BOJ', 10),
('트리 순회', 'https://www.acmicpc.net/problem/1991', 'TREE', 'BOJ', 10),
('완전 이진 트리', 'https://www.acmicpc.net/problem/9934', 'TREE', 'BOJ', 10),
('트리', 'https://www.acmicpc.net/problem/1068', 'TREE', 'BOJ', 11),
('나무 위의 빗물', 'https://www.acmicpc.net/problem/17073', 'TREE', 'BOJ', 11),
('사촌', 'https://www.acmicpc.net/problem/9489', 'TREE', 'BOJ', 12),
('트리의 기둥과 가지', 'https://www.acmicpc.net/problem/20924', 'TREE', 'BOJ', 12),
('이진 검색 트리', 'https://www.acmicpc.net/problem/5639', 'TREE', 'BOJ', 12),
('트리의 지름', 'https://www.acmicpc.net/problem/1967', 'TREE', 'BOJ', 12),
('가장 가까운 공통 조상', 'https://www.acmicpc.net/problem/3584', 'TREE', 'BOJ', 12),
('트리의 높이와 너비', 'https://www.acmicpc.net/problem/2250', 'TREE', 'BOJ', 14),
('트리', 'https://www.acmicpc.net/problem/4256', 'TREE', 'BOJ', 14),
('트리의 순회', 'https://www.acmicpc.net/problem/2263', 'TREE', 'BOJ', 15);

-- Description: Insert trie recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('문자열 집합', 'https://www.acmicpc.net/problem/14425', 'TRIE', 'BOJ', 7),
('생태학', 'https://www.acmicpc.net/problem/4358', 'TRIE', 'BOJ', 9),
('전화번호 목록', 'https://www.acmicpc.net/problem/5052', 'TRIE', 'BOJ', 12),
('문자열 지옥에 빠진 호석', 'https://www.acmicpc.net/problem/20166', 'TRIE', 'BOJ', 12),
('개미굴', 'https://www.acmicpc.net/problem/14725', 'TRIE', 'BOJ', 13);

-- Description: Insert two_pointer recommended problems data into the database
INSERT INTO problem (title, url, category, platform, difficulty) VALUES
('배열 합치기', 'https://www.acmicpc.net/problem/11728', 'TWO_POINTER', 'BOJ', 6),
('블로그', 'https://www.acmicpc.net/problem/21921', 'TWO_POINTER', 'BOJ', 8),
('겹치는 건 싫어', 'https://www.acmicpc.net/problem/20922', 'TWO_POINTER', 'BOJ', 10),
('두 용액', 'https://www.acmicpc.net/problem/2470', 'TWO_POINTER', 'BOJ', 11),
('가장 긴 짝수 연속한 부분 수열 (large)', 'https://www.acmicpc.net/problem/22862', 'TWO_POINTER', 'BOJ', 11),
('합이 0', 'https://www.acmicpc.net/problem/3151', 'TWO_POINTER', 'BOJ', 12),
('부분합', 'https://www.acmicpc.net/problem/1806', 'TWO_POINTER', 'BOJ', 12),
('회전 초밥', 'https://www.acmicpc.net/problem/15961', 'TWO_POINTER', 'BOJ', 12),
('팀 빌딩', 'https://www.acmicpc.net/problem/22945', 'TWO_POINTER', 'BOJ', 12),
('같이 눈사람 만들래?', 'https://www.acmicpc.net/problem/20366', 'TWO_POINTER', 'BOJ', 13),
('합이 0인 네 정수', 'https://www.acmicpc.net/problem/7453', 'TWO_POINTER', 'BOJ', 14),
('ㅋㅋ루ㅋㅋ', 'https://www.acmicpc.net/problem/20442', 'TWO_POINTER', 'BOJ', 14),
('광부 호석', 'https://www.acmicpc.net/problem/21279', 'TWO_POINTER', 'BOJ', 16);
